
VERSION 0.6
PROJECT earthly-sa/earthly-demo

main-pipeline:
  PIPELINE 
  TRIGGER push main 
  TRIGGER pr main 
  BUILD +all-docker


all-docker:
  BUILD ./quote_client/+docker
  BUILD ./rust_server/+docker

dev-up:
  LOCALLY
  RUN docker-compose up


dev-down:
  LOCALLY
  RUN docker-compose down
