VERSION --global-cache 0.7
IMPORT github.com/earthly/lib/rust:2.2.10 AS rust

FROM  rust:slim-buster
WORKDIR /rust-server

build:
  DO rust+INIT --keep_fingerprints=true
  COPY Cargo.lock Cargo.toml Rocket.toml quotes.txt .
  COPY --dir src .
  DO rust+CARGO --args="build --release --bin quote_server" --output="release/[^/\.]+"
  SAVE ARTIFACT target/release/quote_server quote_server

test:
  FROM +build
  DO rust+CARGO --args="test"

docker:
  ARG --required tag
  FROM debian:buster-slim
  COPY +build/quote_server quote_server
  # We also have to copy Rocket.toml so that Rocket binds to the correct address and port within the container.
  COPY Rocket.toml Rocket.toml
  COPY ../quote_generator+artifact/quotes.txt quotes.txt
  EXPOSE 8000
  ENTRYPOINT ["./quote_server"]
  SAVE IMAGE --push ezeev/earthly-rust-example:$tag
