VERSION 0.7

FROM rust:1.66-slim-buster
WORKDIR /rust-server


deps:
  COPY --dir src Cargo.lock Cargo.toml Rocket.toml quotes.txt .
  
test:
  FROM +deps
  RUN cargo test

build:
  FROM +deps
  RUN cargo build --release --bin quote_server
  SAVE ARTIFACT target/release/quote_server quote_server

docker:
  ARG --required tag
  FROM debian:buster-slim
  COPY +build/quote_server quote_server
  # We also have to copy Rocket.toml so that Rocket binds to the correct address and port within the container.
  COPY Rocket.toml Rocket.toml
  COPY ../quote_generator+artifact/quotes.txt quotes.txt
  EXPOSE 8000
  ENTRYPOINT ["./quote_server"]
  SAVE IMAGE --push ezeev/earthly-rust-example:$tag
