VERSION 0.7
FROM node:19.5.0-buster-slim 
WORKDIR /quote-client

deps:
  COPY --dir src public index.html package.json tsconfig.json tsconfig.node.json vite.config.ts yarn.lock .
  RUN yarn global add typescript
  RUN yarn
  
build:
  FROM +deps
  ARG --required rust_server
  ARG --required go_server
  RUN VITE_RUST_SERVER=$rust_server \
    VITE_GO_SERVER=$go_server \
    yarn build
  SAVE ARTIFACT dist/ 

docker:
  FROM nginx:latest 
  ARG --required tag
  COPY +build/dist /usr/share/nginx/html/
  EXPOSE 80 
  SAVE IMAGE --push ezeev/earthly-react-example:$tag

