[package]
name = "quote_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#time = "0.1.12"
regex = "0.1.41"
rocket = "0.5.0-rc.2"
rand = "0.8.5"
