VERSION 0.7
PROJECT earthly-sa/earthly-demo

FROM rust:1.66-slim-buster
WORKDIR /rust-server

rust-server-pipeline:
  PIPELINE 
  TRIGGER push main 
  TRIGGER pr main 
  BUILD +build


deps:
  COPY --dir src Cargo.lock Cargo.toml Rocket.toml .
  
test:
  FROM +deps
  RUN cargo test

build:
  FROM +deps
  RUN cargo build --release --bin quote_server
  SAVE ARTIFACT target/release/quote_server quote_server

docker:
  FROM debian:buster-slim
  COPY +build/quote_server quote_server
  # We also have to copy Rocket.toml so that Rocket binds to the correct address and port within the container.
  COPY Rocket.toml Rocket.toml
  EXPOSE 8000
  ENTRYPOINT ["./quote_server"]
  SAVE IMAGE ezeev/earthly-rust-example:latest
