VERSION 0.7
FROM node:19.5.0-buster-slim 
WORKDIR /quote-client

deps:
  COPY --dir src index.html package.json tsconfig.json tsconfig.node.json postcss.config.cjs tailwind.config.cjs vite.config.ts yarn.lock .
  COPY --dir public .
  RUN yarn global add typescript
  RUN yarn

test:
  FROM +deps
  RUN ls public/
  RUN echo TODO: Implement react tests here

build:
  FROM +deps
  ARG --required base_url   
  RUN VITE_RUST_SERVER=$base_url:8000 \
    VITE_GO_SERVER=$base_url:8001 \
    VITE_PYTHON_SERVER=$base_url:8002 \
    VITE_NODE_SERVER=$base_url:8003 \
    yarn build
  SAVE ARTIFACT dist/ 

docker:
  FROM nginx:latest 
  ARG --required tag
  COPY +build/dist /usr/share/nginx/html/
  EXPOSE 80 
  SAVE IMAGE --push ezeev/earthly-react-example:$tag
