VERSION 0.7
FROM golang:1.19.5-alpine3.17
WORKDIR /go-server

deps:
  COPY go.mod go.sum ./
  RUN go mod download
  SAVE ARTIFACT go.mod 
  SAVE ARTIFACT go.sum 

test:
  FROM +deps 
  COPY main.go quotes.go quotes_test.go .
  RUN go test -v -vet=off # vet=off prevents us from having to install gcc to run tests. See: https://github.com/golang/go/issues/42996


build:
  FROM +deps
  COPY main.go quotes.go .
  RUN go build -o build/go-server .
  SAVE ARTIFACT build/go-server go-server 

docker:
  COPY +build/go-server . 
  EXPOSE 8001
  ENTRYPOINT ["./go-server"]
  SAVE IMAGE --push ezeev/earthly-go-example:latest
