name: GH-Actions-Satellites

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  satellites-build:
    environment: "Actions Demo"
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      FORCE_COLOR: 1
      EARTHLY_LOGSTREAM_UPLOAD: true
    steps:
      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.7.21
      - uses: actions/checkout@v2
      - name: Put back the git branch into git (Earthly uses it for tagging)
        run: |
          branch=""
          if [ -n "$GITHUB_HEAD_REF" ]; then
            branch="$GITHUB_HEAD_REF"
          else
            branch="${GITHUB_REF##*/}"
          fi
          git checkout -b "$branch" || true
      - name: Docker Login
        run: docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_TOKEN"
      - name: Earthly version
        run: earthly --version
      - name: Run CI pipeline
        run: "earthly --ci --sat evan1 --org earthly-sa --push +main-pipeline --tag=gh-sat-demo"
