name: GH-Actions-Demo

on:
  push:
    branches:
      - "gh-actions-demo"
  pull_request:
    branches:
      - "gh-actions-demo"
jobs:
  sat1:
    environment: "Actions Demo"
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      FORCE_COLOR: 1
      EARTHLY_LOGSTREAM_UPLOAD: true
    steps:
    - uses: earthly/actions/setup-earthly@v1
      with:
        version: v0.7.0
    - uses: actions/checkout@v2
    - name: Put back the git branch into git (Earthly uses it for tagging)
      run: |
        branch=""
        if [ -n "$GITHUB_HEAD_REF" ]; then
          branch="$GITHUB_HEAD_REF"
        else
          branch="${GITHUB_REF##*/}"
        fi
        git checkout -b "$branch" || true
    - name: Docker Login
      run: docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_TOKEN"
    - name: Earthly version
      run: earthly --version
    - name: Run all tests  
      run: > 
        parallel --linebuffer ::: 
        "earthly --sat evan1 --org earthly-sa ./examples/polyglot-repo/python_server+test" 
        "earthly --sat evan2 --org earthly-sa ./examples/polyglot-repo/go_server+test"
        && echo OK - All tests completed successfully 
    - name: Build and push images  
      run: > 
        parallel --linebuffer ::: 
        "earthly --push --sat evan1 --org earthly-sa ./examples/polyglot-repo/python_server+docker --tag=gh-actions-parallel"
        "earthly --push --sat evan2 --org earthly-sa ./examples/polyglot-repo/go_server+docker --tag=gh-actions-parallel"
        && echo OK - All builds completed successfully
